matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_AU
  sources:
  - 'src/content/writeups/**/*.md'
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - pymdownx.inlinehilite
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  default_encoding: utf-8
