matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_AU
    # Maximum relaxation settings
    ignore-case: false
    run-together: true
    run-together-limit: 50
    ignore-accents: true
    camel-case: true
    # Only flag words with high edit distance from known words
    sug-mode: ultra
    # Set a very high relaxation threshold
    relaxed: true
    # Ignore all-caps words (acronyms)
    ignore-all-caps: true
  sources:
  - 'src/content/writeups/**/*.md'
  - 'src/content/tools/**/*.md'
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - pymdownx.inlinehilite
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  default_encoding: utf-8