matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_AU
    # Set a higher threshold for what counts as a misspelling
    sug-mode: fast
    ignore-case: true
    # Only flag words that are very likely to be misspellings
    guess: true
    ignore-accents: true
    camel-case: true
  sources:
  - 'src/content/writeups/**/*.md'
  - 'src/content/tools/**/*.md'
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - pymdownx.inlinehilite
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  default_encoding: utf-8