name: Spellcheck

on:
  push:
    branches: ["main"]
    paths:
      - 'src/content/writeups/**/*.md'
      - 'src/content/tools/**/*.md'
  pull_request:
    branches: ["main"]
    paths:
      - 'src/content/writeups/**/*.md'
      - 'src/content/tools/**/*.md'
  workflow_dispatch:

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.48.0
        with:
          source_files: 'src/content/writeups/**/*.md src/content/tools/**/*.md'
          task_name: Markdown
          output_file: spellcheck-output.txt
